package com.trustai.userservice.user.exception;


import com.trustai.userservice.user.exception.base.UserValidationException;

public class RecordNotFoundExceptionUser extends UserValidationException {
}
